### PR TITLE
Improve bootstraping

### PR DESCRIPTION
**Pull request by mbohal**
This PR improves the bootstraping.

It is functionally same as the old version, but it relies on autoloading instead of `require()`. This allows the code to be statically analysed and enables the use of autocomplete in IDEs and other tools.

### CODE REVIEW

**Comment by mbohal** [comment]
@nyamsprod That would probably work as well, but how is it better?

Whenever possible I prefer to use the most obvious and easy to read way of doing things. Is there some advantage in the method you suggest that I'm not aware off?

**Comment by nyamsprod** [comment]
@mbohal a class which is static and has only one method is... a function in my book :smile: . So the most obvious thing to do IMHO is to create functions not classes. functions are PHP's simplest unit of code not classes.

If your were doing complex things that requires interactions with multiples services I then would agree with your approach of adding classes but then you would have to instantiate them properly (no static methods) to take into account those interactions which means something completely different from your PR goals if I understand it clearly.

My suggestion meets all your requirements and even offload all file inclusions to composer with the exception of the settings array.

**Comment by mbohal** [comment]
I dislike that in order to find out where the `dependencies()` function comes from I have to look into `composer.json`

> So the most obvious thing to do IMHO is to create functions not classes. functions are PHP's simplest unit of code not classes.

I'm not sure if I agree fully. I think the PHP autoloading makes class the natural logical unit to include. Including functions directly works nice in, for example JS and Python, but in PHP it just feels awkward to me. 

Either way is better then the current implementation though. Let the repo maintainer decide. If he/she sais so, Ill rewrite the PR your way.

**Comment by nyamsprod** [comment]
>  I dislike that in order to find out where the `dependencies()` function comes from I have to look into `composer.json`

@mbohal your IDE will find the `dependencies` function do not worry about that.

> Either way is better then the current implementation though. Let the repo maintainer decide. If he/she sais so, Ill rewrite the PR your way.

Indeed, let them decide 👍

**Pull request merged**
