### PR TITLE
Pulled procedural code from external files into index.php

### PR DESCRIPTION
**Pull request by gargoyle**
I don't think its a good idea to promote spreading procedural code (which essentially uses `$app` as a global variable) across multiple files.

If the idea is to promote file organisation, then we should update the app to use controller classes.

If the idea is to have the simplest working application, then I don't think a 55 line index.php breaks the bank.

I've left `settings.php` as it is because it is a stand alone file which doesn't depend on `$app`.

### CODE REVIEW

**Comment by codeguy** [comment]
Pulling Rob in since he is the author of this example app.

/cc @akrabat

**Comment by geggleto** [comment]
👎 

It is considered best practice to split out certain aspects of the application bootstrap.

Consider the following example.

### I want to use the Container in my unit tests.

I do not need Slim or to register Routes to Slim. I only need to add the container entries and any other dependencies.

**Comment by gargoyle** [comment]
geggleto, I agree. 

Please let me know how you would pull in the current `src/dependencies.php` into a unit test where you don't have a Slim app already configured?

**Comment by akrabat** [comment]
One reason why the skeleton has separate files is that even in a microframework, some organisation is required for routes, DI config and middleware.

I remain to be convinced that a class is required for route or middleware registration.

There's also an argument that rather than using a closure for the route callable, there could be a class for that, but we run the risk of making the learning curve significantly higher.

**Comment by akrabat** [comment]
I'm against this particular solution to the problem. Happy to have more discussion about it in an issue though. If we agree that improvements can be made that work for this project, then we can look at a PR for the changes.

**Pull request closed without merging**
