### PR TITLE
update docker-compose.yml

### PR DESCRIPTION
**Pull request by tomtomsen**
I needed that change to make docker-compose up work.
Otherwise i got: Fatal error: Unknown: Failed opening required '/var/www/public/public/index.php' (include_path='.:/usr/local/lib/php') in Unknown on line 0

### CODE REVIEW

**Comment by geggleto** [comment]
I might replace this with a proper nginx docker config; do think think that would be a better option @tomtomsen ?

**Comment by tomtomsen** [comment]
@geggleto 
i think that would be too much. 
the purpose of the docker-composer file should be to be able to get into the code an play with it. it should be simple, easy and distraction free, additional nginx/fpm/... config files aren't worth it.

i believe most of the people who clone this repo, are new to slim (like me) and just want to get a feeling for the framework.

**Comment by silentworks** [comment]
Thank you @tomtomsen

**Comment by silentworks** [comment]
@tomtomsen can I ask a favour, can you try updating your docker-compose.yml to use

```
command: php -S 0.0.0.0:8080 -t public
```

and let me know if this works, it seems your PR broke Docker setup for some others and the code above seem to be a middle ground, so if that works for you then we can get a new PR with that in.

//cc @svpernova09

**Comment by tomtomsen** [comment]
@silentworks that statement works perfectly fine in my setup.

steps if done:
```
1. git clone ...
2. composer update
3. docker-compose up
4. open localhost:8080
```

well done

**Comment by silentworks** [comment]
@tomtomsen Its not clear if you edited your `docker-compose.yml` before running `docker-compose up`.

steps to do:

```
1. git clone ...
2. composer install
3. edit docker-compose.yml and change line 11 to command: php -S 0.0.0.0:8080 -t public
4. docker-compose up
5. open localhost:8080
```

**Comment by tomtomsen** [comment]
@silentworks stupid me. i forgot to mention the most important step. i did all 5! steps and it worked on my setup.

steps i (actually) did:
```
1. git clone ...
2. composer install
3. edit docker-compose.yml and change line 11 to command: php -S 0.0.0.0:8080 -t public
4. docker-compose up
5. open localhost:8080
```

i even checked it again to be 100% sure.
thanks

**Comment by silentworks** [comment]
Thank you so much @tomtomsen

**Pull request merged**
