### PR TITLE
Updated syntax to apache 2.4. version.

### PR DESCRIPTION
**Pull request by Vakrug**
Related to issue #313. Removed old 2.2. syntax and updated with the equivalent 2.4. syntax.

### CODE REVIEW

**Comment by eugene-borovov** [comment]
Why not do it as in the default configuration?

```
#
# The following lines prevent .htaccess and .htpasswd files from being 
# viewed by Web clients. 
#
<Files ".ht*">
    Require all denied
</Files>
```

**Comment by Vakrug** [comment]
> Why not do it as in the default configuration?
Because ".ht*" and ".htaccess" are different things, as the comment says (.htpasswd exists). This redirection to index page have nothing to do with .htpasswd.

**Comment by eugene-borovov** [comment]
This directive denies access to files with name starts with `.ht`. This rule is usually placed in the server settings, not the host. As you mentioned in the issue this directive could be deleted. 

For redirection you only need rewrite rules.

```
<IfModule mod_rewrite.c>
  # Redirect to the public folder
  RewriteEngine On
  # RewriteBase /
  RewriteRule ^$ public/ [L]
  RewriteRule (.*) public/$1 [L]

  # Redirect to HTTPS
  # RewriteEngine On
  # RewriteCond %{HTTPS} off
  # RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</IfModule>

```

**Comment by Vakrug** [comment]
OK, I deleted this directive.

**Pull request merged**
