### PR TITLE
Add some Improvement

### PR DESCRIPTION
**Pull request by agungaprianto**
in this pull request i added some improvement : 

- update some documentation
- add one parameter in action's constructor for getting key from container
- add variable for accessing container interface and array in settings.php

### CODE REVIEW

**Comment by l0gicgate** [comment]
Injecting the `ContainerInterface` inside of actions is an anti-pattern. Sorry, we will not be adding this.

**Comment by idle-user** [comment]
Probably not the best way to go about it, but if for some reason you need to access specific values throughout many actions, add them in a middleware to access them later.

`$request = $request->withAttribute('key', value);`

`$this->request->getAttribute('key');`

**Comment by l0gicgate** [comment]
If you want to inject specific settings into your actions you should inject them via a generator function when instantiating your action on a container definition. Or make a `Settings` class and map it to your container so you can easily inject it into your actions as a dependency.

**Comment by agungaprianto** [comment]
ok i'll create generator function for mapping settings and put it into action , because we can easily put some value and get it from settings for certain case

**Pull request closed without merging**
